<a href="https://colab.research.google.com/github/Ani888/Text-Preprocessing-GenerativeAI/blob/main/Text_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataset : https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [ ]:
import pandas as pd

In [ ]:
!pwd

/content

In [ ]:
data_path="/content/IMDB Dataset.csv"

In [ ]:
df = pd.read_csv(data_path)

In [ ]:
df.shape

(50000, 2)

In [ ]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df = df.head(100)

In [ ]:
df.shape

(100, 2)

lower case operation in data preprocessing

In [ ]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [ ]:
df['review']=df['review'].str.lower()

In [ ]:
df

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production. <br /><br />the...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there's a family where a little boy ...  negative
4   petter mattei's "love in the time of money" is...  positive
..                                                ...       ...
95  daniel day-lewis is the most versatile actor a...  positive
96  my guess would be this was originally going to...  negative
97  well, i like to watch bad horror b-movies, cau...  negative
98  this is the worst movie i have ever seen, as w...  negative
99  i have been a mario fan for as long as i can r...  positive

[100 rows x 2 columns]

In [ ]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

# ***remove html tag in data preprocessing***

In [ ]:
import re
def remove_html_tag(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'',text)

In [ ]:
text = """<html><head><title>Sentiment Analysis</title></head><body><h1>Amazing Product!</h1><p>I REALLY love this product!!! 😍</p><p>The quality is <b>excellent</b>, but the delivery was slow.</p><a href="https://example.com">Click here</a></body></html>"""

In [ ]:
remove_html_tag(text)

'Sentiment AnalysisAmazing Product!I REALLY love this product!!! 😍The quality is excellent, but the delivery was slow.Click here'

In [ ]:
df['review']=df['review'].apply(remove_html_tag)

In [ ]:
df['review'][7]

"this show was an amazing, fresh & innovative idea in the 70's when it first aired. the first 7 or 8 years were brilliant, but things dropped off after that. by 1990, the show was not really funny anymore, and it's continued its decline further to the complete waste of time it is today.it's truly disgraceful how far this show has fallen. the writing is painfully bad, the performances are almost as bad - if not for the mildly entertaining respite of the guest-hosts, this show probably wouldn't still be on the air. i find it so hard to believe that the same creator that hand-selected the original cast also chose the band of hacks that followed. how can one recognize such brilliance and then see fit to replace it with such mediocrity? i felt i must give 2 stars out of respect for the original cast that made this show such a huge success. as it is now, the show is just awful. i can't believe it's still on the air."

# ***remove url in data preprocessing***

In [ ]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub('', text)

In [ ]:
text1="check my youtube url https://www.youtube.com/watch?v=IG-tM_4iKOg&list=PLZXDzqthZtF8"

In [ ]:
remove_url(text1)

'check my youtube url '

# ***panctuation handling***

In [ ]:
import string, time
exclude = string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
def remove_punc(text):
  for char in exclude :
    text= text.replace(char,'')
    return text

In [ ]:
text="""String. With. Punctuation?"""

In [ ]:
start=time.time()
print(remove_punc(text))
time1 = time.time() - start
print(time1*50000)

String. With. Punctuation?
114.44091796875

# ***another approach to remove punctuation***

In [ ]:
def remove_punc1(text):
  return text.translate(str.maketrans('','',exclude))

In [ ]:
start=time.time()
print(remove_punc1(text))
time2 = time.time() - start
print(time2*50000)

String With Punctuation
31.518936157226562

In [ ]:
remove_punc1(df['review'][5])

'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'

# ***chat conversation handle ( in this we give lots of shortcut in chat )***

In [ ]:
# create dictionary for all the shortcut first
chat_words = {
    'AFAIK':'As far as I know',
    'AFK':'Away from keyboard',
    'ASAP': 'As soon as possible'
}

In [ ]:
def chat_conversion(text):
  new_text=[]
  for w in text.split():
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)
  return " ".join(new_text)

In [ ]:
chat_conversion("Do  this  work  ASAP")

'Do this work As soon as possible'

# ***incorrect text handling that is spelling mistakes***

In [ ]:
# to handle the spelling mistake i have to use textblob to import TextBlob
from textblob import TextBlob
incorrect_text =" Thisss product is sooo good I luvvv ittt but the delivery was verry baddd"
textBlb = TextBlob(incorrect_text)
print(textBlb.correct())

 Hiss product is soon good I luvvv it but the delivery was very added

# ***Stop word which does not support in positive or negative sentiment***

In [ ]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [ ]:
len(stopwords.words('english'))

198

In [ ]:
def remove_stopwords(text):
  new_text =[]
  for word in text.split():
    if word in stopwords.words('english'):
      new_text.append('')
    else:
      new_text.append(word)

  x = new_text[ : ]
  new_text.clear()
  return " ".join(x)

In [ ]:
remove_stopwords('This is a very good product and it is available at a reasonable price. The delivery was late, but the quality of the product is excellent. I would like to recommend this product to my friends and family. It is one of the best products in the market.')

'This    good product    available   reasonable price. The delivery  late,   quality   product  excellent. I would like  recommend  product   friends  family. It  one   best products   market.'

In [ ]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [ ]:
df['review'].apply(remove_stopwords)

0     one    reviewers  mentioned   watching  1 oz e...
1      wonderful little production.  filming techniq...
2      thought    wonderful way  spend time    hot s...
3     basically there's  family   little boy (jake) ...
4     petter mattei's "love   time  money"   visuall...
                            ...
95    daniel day-lewis    versatile actor alive. eng...
96     guess would    originally going    least two ...
97    well,  like  watch bad horror b-movies, cause ...
98       worst movie   ever seen,  well as,  worst  ...
99        mario fan   long    remember,    fond memo...
Name: review, Length: 100, dtype: object

# ***remove emoji handle***

In [ ]:
import re
def remove_emoji(text):
  emoji_pattern= re.compile("["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002600-\U000026FF"
        "\U00002700-\U000027BF""]+",flags=re.UNICODE)
  return emoji_pattern.sub(r'', text)

In [ ]:
remove_emoji('😍😍 This product is sooo good 🔥🔥 I love the quality ❤️ but the delivery was bad 😡😡')

' This product is sooo good  I love the quality ️ but the delivery was bad '

In [ ]:
!pip install emoji

Requirement already satisfied: emoji in /usr/local/lib/python3.13/dist-packages (2.16.0)

In [ ]:
import emoji
print(emoji.demojize('😍😍 This product is sooo good 🔥🔥'))

:smiling_face_with_heart-eyes::smiling_face_with_heart-eyes: This product is sooo good :fire::fire:

# ***Tokenization***

1. split function

In [ ]:
# word tokenization
sent1='I will get high paying job very soon'
sent1.split()

['I', 'will', 'get', 'high', 'paying', 'job', 'very', 'soon']

In [ ]:
# sentence tokenization
sent2='I am going to get very high paying job very very soon. My job title will be AI/ML engineer. This going to happen very very soon'
sent2.split('.')

['I am going to get very high paying job very very soon',
 ' My job title will be AI/ML engineer',
 ' This going to happen very very soon']

In [ ]:
# proble with split function in word tokenization  it consider ! mark with word not separate
sent3='I got the very very high paying job!'
sent3.split()

['I', 'got', 'the', 'very', 'very', 'high', 'paying', 'job!']

In [ ]:
# proble with split function in word tokenization it ignore ?
sent4='I got the very very high paying job with god grace. I become AI/ML engineer. Should I join today? I have litle time celebrate and thank to god'
sent4.split('.')

['I got the very very high paying job with god grace',
 ' I become AI/ML engineer',
 ' Should I join today? I have litle time celebrate and thank to god']

2. With regular expression

In [ ]:
import re
sent5=" I am going to get very very high paying job!"
tokens = re.findall(r"\w+",sent5)
tokens

['I', 'am', 'going', 'to', 'get', 'very', 'very', 'high', 'paying', 'job']

In [ ]:
text=""" I got very very high paying job in MNC. My role is AI/ML engineer there. Shouls i join today? I have 2 more days to join and enjoy the success"""
sentence = re.compile('[.!?]').split(text)
sentence

[' I got very very high paying job in MNC',
 ' My role is AI/ML engineer there',
 ' Shouls i join today',
 ' I have 2 more days to join and enjoy the success']

3. NLKT ( Natural Language Toolkit) used here for tokenization

In [ ]:
from nltk.tokenize import word_tokenize, sent_tokenize
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
sent6="I got the very very high paying job in MNC for AI/ML role!"
word_tokenize(sent6)

['I',
 'got',
 'the',
 'very',
 'very',
 'high',
 'paying',
 'job',
 'in',
 'MNC',
 'for',
 'AI/ML',
 'role',
 '!']

In [ ]:
sent7=" I got the very very high paying job!. My role is AI/ML engineer. It is a MNC company"
sent_tokenize(sent7)

[' I got the very very high paying job!.',
 'My role is AI/ML engineer.',
 'It is a MNC company']

4. Spacy (this also used to perform tokenization

In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [ ]:
doc1=nlp(sent5)
doc2=nlp(sent6)
doc3=nlp(sent7)
doc4=nlp(sent1)

In [ ]:
doc4=nlp(sent1)
doc4

I will get high paying job very soon

In [ ]:
for token in doc4:
  print(token)

I
will
get
high
paying
job
very
soon

In [ ]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

# ***Stemmer (convert 2nd and 3rd form of verb into first form. example walk, walks, walked, walking. this are all converted to walk, walk, walk, walk by stemmer)***

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
ps=PorterStemmer()
def stem_word(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [ ]:
sample=" walk walks walking walked "
stem_word(sample)

'walk walk walk walk'

In [ ]:
text=" I got very very high paying job in MNC. My role is AI/ML engineer. I will join the comapny very soon"
stem_word(text)

'i got veri veri high pay job in mnc. my role is ai/ml engineer. i will join the comapni veri soon'

# ***Lemmatization (It change or give readable word)***

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')
wordnet_lemmatizer = WordNetLemmatizer()

sentence = " I got very very high paying job in MNC. My role is AI/ML engineer. I am going to join company with two days."
punctuation ="?:!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
  if word in punctuation:
    sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
  print("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word, pos='v')))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

Word                Lemma
I                   I
got                 get
very                very
very                very
high                high
paying              pay
job                 job
in                  in
MNC                 MNC
My                  My
role                role
is                  be
AI/ML               AI/ML
engineer            engineer
I                   I
am                  be
going               go
to                  to
join                join
company             company
with                with
two                 two
days                days